# Generated by Django 3.2.4 on 2021-07-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auto',
            old_name='name',
            new_name='nickname',
        ),
    ]
